### ISSUE TITLE
Choice around manually entered urls

### ISSUE THREAD

**Issue by CosineP** [losingkeys/dmenu-custom#2]
Hello losingkeys,

The format of ~/.dmenu-web seems well-designed to me, I was just wondering why you don't check for url-like dmenu entries if they are entered? I figured I'd add it, but it seems like a big enough (and obvious enough) change that I should ask what the rationale was.

**Comment by losingkeys** [comment]
I didn't want to type the full URL (not sure it even occurred to me). Feel free to add it.

Eventually it'd be cool if this could pull data (site names/URLs) from firefox/chromium... but then the names might be longer/not exactly the aliases you wanted.

**Comment by CosineP** [comment]
Ah, like from history and bookmarks, that's a good idea! Maybe another time. I'll add checking for urls in to my pull request and then it'll be done.
